### ISSUE TITLE
Accessible HTML

### ISSUE THREAD

**Issue by boushka9** [coding-boot-camp/urban-octo-telegram#44]
GIVEN a webpage meets accessibility standards
WHEN I view the source code
THEN I find semantic HTML elements
WHEN I view the structure of the HTML elements
THEN I find that the elements follow a logical structure independent of styling and positioning
WHEN I view the image elements
THEN I find accessible alt attributes
WHEN I view the heading attributes
THEN they fall in sequential order
WHEN I view the title element
THEN I find a concise, descriptive title

**Comment by Cxxrupt** [comment]
Semantic HTML is in order
Alt Attributes have been added
